const ENDPOINT = window.EVENTWISE_CONFIG?.N8N_WEBHOOK_URL?.trim();
const state = { token: localStorage.getItem('eventwise_token') || '', user: JSON.parse(localStorage.getItem('eventwise_user') || 'null'), plan: null, version: 0, poller: null };
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const arr = v => Array.isArray(v) ? v : [];
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);

function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 4200); }
async function api(body) { if (!ENDPOINT) throw new Error('EventWise is not configured. Add the n8n webhook URL to config.js.'); const response = await fetch(ENDPOINT,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)}); let data; try { data = await response.json(); } catch { throw new Error('The planning service returned an invalid response.'); } data=Array.isArray(data)?data[0]:data; if (!response.ok || !data || data.success === false) throw new Error(data?.error || data?.message || 'Something went wrong. Please try again.'); return data; }
function setSession(data) { state.token=data.token; state.user=data.user; localStorage.setItem('eventwise_token',data.token); localStorage.setItem('eventwise_user',JSON.stringify(data.user)); updateAuthUI(); }
function clearSession() { state.token='';state.user=null;state.plan=null;localStorage.removeItem('eventwise_token');localStorage.removeItem('eventwise_user');clearInterval(state.poller);const results=$('#my-plan');if(results)results.hidden=true;updateAuthUI(); }
function updateAuthUI(){ const actions=$('.header-actions'); if(state.user) actions.innerHTML=`<button class="text-button" id="my-plan-button">${esc(state.user.name?.split(' ')[0] || 'My plan')}</button><button class="button small" id="logout-button">Logout</button>`; else actions.innerHTML='<button class="text-button auth-open" data-mode="login">Sign in</button><button class="button small auth-open" data-mode="signup">Create plan</button>'; bindDynamicButtons(); }
function bindDynamicButtons(){ document.querySelectorAll('.auth-open').forEach(b=>b.onclick=()=>openAuth(b.dataset.mode)); $('#logout-button')?.addEventListener('click',handleLogout); $('#my-plan-button')?.addEventListener('click',getSavedPlan); }
function openAuth(mode='login'){ const signup=mode==='signup'; $('#auth-modal').hidden=false; document.body.classList.add('modal-open'); $('#auth-title').textContent=signup?'Create your account':'Welcome back'; $('#auth-subtitle').textContent=signup?'Save your event plans and return to them anytime.':'Sign in to view and create your saved plans.'; $('#name-field').hidden=!signup; $('#name-field input').required=signup; $('#auth-form').dataset.mode=mode; $('#auth-form button').innerHTML=(signup?'Create account':'Sign in')+' <span>→</span>'; $('#auth-switch').textContent=signup?'Already have an account? Sign in':'New here? Create an account'; setTimeout(()=>$('#auth-form label:not([hidden]) input')?.focus(),30); }
function closeAuth(){ $('#auth-modal').hidden=true; document.body.classList.remove('modal-open'); }
async function handleAuth(e){ e.preventDefault(); const f=new FormData(e.currentTarget), mode=e.currentTarget.dataset.mode; const btn=e.currentTarget.querySelector('button'); btn.disabled=true; btn.textContent='Please wait…'; try { const data=await api({action:mode,name:f.get('name'),email:f.get('email'),password:f.get('password')}); setSession(data); closeAuth(); toast(data.message || 'Welcome to EventWise.'); if(data.plan) displayEventPlan(data.plan,data); else $('#plan').scrollIntoView({behavior:'smooth'}); } catch(err){toast(err.message);} finally {btn.disabled=false;btn.innerHTML=(mode==='signup'?'Create account':'Sign in')+' <span>→</span>';}}
async function handleLogout(){ try{await api({action:'logout',token:state.token});}catch{} clearSession();toast('You have been logged out.'); }
function validateForm(data){ if(!data.eventType||!data.location||!data.date||!data.preferences) return 'Please complete all event details.'; if(Number(data.guests)<1)return 'Please enter at least one guest.';if(Number(data.budget)<=0)return 'Please enter a valid budget.';return ''; }
function planning(show){ $('#loading').hidden=!show; if(show){$('#loading').scrollIntoView({behavior:'smooth',block:'center'}); let i=0; const messages=['Understanding your event…','Planning the schedule…','Balancing your budget…','Thinking about your guests…','Preparing backup options…','Checking the weather…','Putting everything together…']; planning.timer=setInterval(()=>$('#loading-message').textContent=messages[++i%messages.length],1700);} else clearInterval(planning.timer); }
async function generateEvent(e){ e.preventDefault(); const form=new FormData(e.currentTarget), payload=Object.fromEntries(form.entries()); payload.guests=Number(payload.guests);payload.budget=Number(payload.budget);const error=validateForm(payload);if(error)return toast(error);if(!state.token){openAuth('signup');toast('Create an account to save your plan.');return;} const btn=e.currentTarget.querySelector('[type=submit]');btn.disabled=true;btn.textContent='Creating your plan…';planning(true);try{const data=await createEventPlan(payload);localStorage.setItem('eventwise_current_plan',JSON.stringify({plan:data.plan,version:data.version,updatedAt:data.updatedAt}));window.location.href='my-plan.html';}catch(err){toast(err.message || 'Unable to create your event plan right now. Please try again.');}finally{planning(false);btn.disabled=false;btn.innerHTML='Create my event plan <span>→</span>';}}
async function createEventPlan(payload){return api({action:'create_plan',token:state.token,...payload});}
function displayEventPlan(plan,response={}){if(!plan)return;state.plan=plan;state.version=response.version || plan.metadata?.version || 0;localStorage.setItem('eventwise_current_plan',JSON.stringify({plan,version:state.version,updatedAt:response.updatedAt||plan.metadata?.generated_at}));const results=$('#my-plan');if(!results)return;$('#empty-plan')&&( $('#empty-plan').hidden=true );results.hidden=false;results.classList.remove('reveal');results.classList.add('visible');results.innerHTML=`<header class="results-header"><div><p class="eyebrow">Your tailored event companion</p><h2>Your Event Plan</h2><p class="block-intro">${esc(plan.event_summary || 'A practical plan, built around your event.')}</p></div><div class="plan-actions"><button class="button secondary" data-action="refresh">Refresh plan</button><button class="button secondary" data-action="update">Save checklist</button><button class="button secondary" onclick="window.print()">Print plan</button><button class="button" data-action="new">New event</button></div></header>${displayEventSummary(plan)}<div class="plan-overview"><span>✦</span><div><b>Everything you need, in one place.</b><p>Work through the checklist, review the schedule, and keep this page handy on event day.</p></div></div><div class="result-grid"><div>${displayBudget(plan)}${displaySchedule(plan)}${displayChecklist(plan)}${displayRecommendations(plan)}</div><aside>${displayWeather(plan)}${displayReadiness(plan)}${displayRisks(plan)}</aside></div><div class="result-grid full-grid">${displayGuestExperience(plan)}${displayVendorRequirements(plan)}${displayAlternativePlans(plan)}${displayCostSavingPlan(plan)}${displayRunSheet(plan)}</div>`; bindPlanInteractions(); results.scrollIntoView({behavior:'smooth',block:'start'});startPolling(); }
function displayEventSummary(p){const e=p.event||{};return `<div class="summary"><div><small>Event</small><b>${esc(e.eventType||'Your event')}</b></div><div><small>Guests</small><b>${esc(e.guests||'—')} people</b></div><div><small>Location</small><b>${esc(e.location||p.location?.name||'—')}</b></div><div><small>Date</small><b>${formatDate(e.date)}</b></div><div><small>Budget</small><b>${money(e.budget)}</b></div></div>`;}
function loadEventImages(p){const terms=arr(p.image_search_terms).length?arr(p.image_search_terms):buildImageQueries(p);return `<div class="gallery">${terms.slice(0,4).map((term,i)=>`<figure><img loading="lazy" src="https://loremflickr.com/900/${i?'600':'1200'}/${encodeURIComponent(term.replace(/\s+/g,','))}?lock=${i+1}" alt="${esc(term)}" onerror="this.parentElement.style.display='none'"><figcaption>${esc(term)}</figcaption></figure>`).join('')}</div>`;}
function buildImageQueries(p){const e=p.event||{};return [`${e.eventType||'event'} celebration`,`${e.eventType||'event'} venue`,`${e.location||''} event decor`,`${e.eventType||'event'} food`];}
function displayBudget(p){const b=p.budget||{}, keys=[['venue','Venue'],['food','Food'],['decoration','Decoration'],['entertainment','Entertainment'],['cake_or_refreshments','Cake / refreshments'],['miscellaneous','Miscellaneous']], total=Number(b.total_estimate)||keys.reduce((s,[k])=>s+(Number(b[k])||0),0), max=Math.max(total,1);return `<section class="plan-block"><h3>Budget breakdown</h3><p class="block-intro"><span class="badge ${/over/i.test(b.status)?'over':''}">${esc(b.status||'Estimate')}</span> Total estimate: <b>${money(total)}</b></p>${keys.map(([k,l])=>`<div class="budget-row"><span>${l}</span><i><b style="width:${Math.min(100,(Number(b[k])||0)/max*100)}%"></b></i><b>${money(b[k])}</b></div>`).join('')}<div class="budget-row total-row"><b>Total estimate</b><i></i><b>${money(total)}</b></div><h4>Savings suggestions</h4><ul class="list-clean">${arr(b.savings_suggestions).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Review your options after vendors provide quotes.</li>'}</ul></section>`;}
function displaySchedule(p){return `<section class="plan-block"><h3>Suggested schedule</h3><div class="timeline">${arr(p.schedule).map(x=>`<div><time>${esc(formatTime(x.time))}</time><p>${esc(x.activity)}</p></div>`).join('')||'<p class="block-intro">Your schedule will appear here.</p>'}</div></section>`;}
function displayChecklist(p){const items=arr(p.checklist);return `<section class="plan-block"><h3>Planning checklist</h3><p class="block-intro" id="check-count">0 of ${items.length} tasks completed</p><div class="check-progress"><i></i></div><div id="checklist">${items.map((x,i)=>`<label class="check-item"><input type="checkbox" data-index="${i}"><span><b>${esc(x.task)}</b><small> · ${esc(x.category||'General')} · ${esc(x.due_phase||'')}</small></span><em class="priority">${esc(x.priority||'Medium')}</em></label>`).join('')}</div></section>`;}
function displayRecommendations(p){return `<section class="plan-block"><h3>EventWise recommendations</h3><ul class="list-clean">${arr(p.recommendations).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Use this plan as a flexible guide and confirm details with your vendors.</li>'}</ul></section>`;}
function displayWeather(p){const w=p.weather_advice||{},icon=/rain|storm/i.test(w.condition)?'☔':/cloud/i.test(w.condition)?'☁':'☀';return `<section class="plan-block weather-card"><span class="weather-icon">${icon}</span><p class="eyebrow">Weather & outdoor planning</p><h4>${esc(w.condition||'Weather details pending')}</h4><span class="badge">${esc(w.outdoor_suitability||'Check closer to date')}</span><p>${esc(w.advice||'Keep a weather backup in place for outdoor activities.')}</p></section>`;}
function displayRisks(p){return `<section class="plan-block"><h3>Risk & backup plan</h3>${arr(p.risks).map(x=>`<article class="risk"><b>${esc(x.risk)} · ${esc(x.severity)}</b><p><b>Trigger:</b> ${esc(x.trigger)}</p><p><b>Mitigation:</b> ${esc(x.mitigation)}</p><p><b>Backup:</b> ${esc(x.backup_plan)}</p></article>`).join('')||'<p class="block-intro">No specific risks returned.</p>'}</section>`;}
function displayGuestExperience(p){const g=p.guest_experience||{};return `<section class="plan-block"><h3>Guest experience</h3><div class="guest-grid"><div><b>Seating</b>${esc(g.seating||'—')}</div><div><b>Food</b>${esc(g.food||'—')}</div><div><b>Activities</b>${esc(arr(g.activities).join(' · ')||'—')}</div><div><b>Accessibility</b>${esc(arr(g.accessibility).join(' · ')||'—')}</div><div><b>Guest flow</b>${esc(g.guest_flow||'—')}</div></div></section>`;}
function table(headers,rows,cls=''){return `<div class="${cls}"><table class="data-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function displayVendorRequirements(p){return `<section class="plan-block"><h3>Vendor requirements</h3>${table(['Category','Required','Quantity / scope','Preparation deadline'],arr(p.vendor_requirements).map(x=>`<tr><td>${esc(x.category)}</td><td>${x.required?'Yes':'Optional'}</td><td>${esc(x.quantity_or_scope)}</td><td>${esc(x.preparation_deadline)}</td></tr>`),'run-sheet')}</section>`;}
function displayReadiness(p){const r=p.readiness||{},score=Math.min(100,Math.max(0,Number(r.score)||0));return `<section class="plan-block readiness"><p class="eyebrow">Event readiness</p><div class="score">${score}<span>/100</span></div><p>${esc(r.status||'In progress')}</p><span class="badge">${arr(r.missing_critical_tasks).length?esc(arr(r.missing_critical_tasks).length+' key tasks left'):'Ready to go'}</span></section>`;}
function displayAlternativePlans(p){const a=p.alternative_plans||{};return `<section class="plan-block"><h3>Alternative ways to plan</h3><div class="plans">${[['Budget plan',a.budget_plan],['Recommended plan',a.recommended_plan],['Premium plan',a.premium_plan]].map(x=>`<article><h4>${x[0]}</h4><p>${esc(x[1]||'Details will be available in your tailored plan.')}</p></article>`).join('')}</div></section>`;}
function displayCostSavingPlan(p){const c=p.cost_saving_plan||{};return `<section class="plan-block"><h3>Save without losing the experience</h3><p class="block-intro">Target reduction: <b>${esc(c.target_reduction_percent||0)}%</b></p><ul class="list-clean">${arr(c.suggestions).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`;}
function displayRunSheet(p){return `<section class="plan-block"><h3>Event day run sheet</h3>${table(['Time','Owner','Task'],arr(p.event_day_run_sheet).map(x=>`<tr><td>${esc(formatTime(x.time))}</td><td>${esc(x.owner)}</td><td>${esc(x.task)}</td></tr>`),'run-sheet')}</section>`;}
function formatDate(s){if(!s)return '—';const d=new Date(s+'T00:00:00');return isNaN(d)?esc(s):d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
function formatTime(value){const raw=String(value??'').trim();if(!raw)return '—';if(/\b(am|pm)\b/i.test(raw))return raw.toUpperCase().replace(/\s+/g,' ');const match=raw.match(/^(\d{1,2}):(\d{2})(?::\d{2})?$/);if(!match)return raw;let hour=Number(match[1]);const minute=match[2];if(hour>23||Number(minute)>59)return raw;const period=hour>=12?'PM':'AM';hour=hour%12||12;return `${hour}:${minute} ${period}`;}
function bindPlanInteractions(){$('[data-action="refresh"]')?.addEventListener('click',()=>getSavedPlan(true));$('[data-action="new"]')?.addEventListener('click',()=>{window.location.href='plan.html';});$('[data-action="update"]')?.addEventListener('click',updateSavedPlan);document.querySelectorAll('#checklist input').forEach(x=>x.addEventListener('change',updateChecklistProgress));updateChecklistProgress();}
function updateChecklistProgress(){const items=[...document.querySelectorAll('#checklist input')],done=items.filter(x=>x.checked).length;items.forEach(x=>x.closest('.check-item').classList.toggle('done',x.checked));const count=$('#check-count');if(count)count.textContent=`${done} of ${items.length} tasks completed`;const bar=$('.check-progress i');if(bar)bar.style.width=(items.length?done/items.length*100:0)+'%';}
async function updateSavedPlan(){if(!state.plan)return;try{const done=[...document.querySelectorAll('#checklist input')].map(x=>x.checked);state.plan.ui_checklist=done;const data=await api({action:'update_plan',token:state.token,plan:state.plan});state.version=data.version;toast('Checklist progress saved.');}catch(e){toast(e.message);}}
async function getSavedPlan(manual=false){if(!state.token){openAuth('login');return;}const refresh=$('[data-action="refresh"]');const label=refresh?.textContent;if(manual&&refresh){refresh.disabled=true;refresh.textContent='Refreshing…';}try{const data=await api({action:'get_plan',token:state.token});if(!data.plan){toast('No saved plan exists in EventWise yet. Create one first.');if($('#planner-form'))$('#planner-form').scrollIntoView({behavior:'smooth'});return;}const changed=state.version&&Number(data.version)>Number(state.version);displayEventPlan(data.plan,data);if(manual)toast(changed?'Your latest plan has been loaded.':'Plan is up to date.');}catch(e){toast(e.message);if(/session|token|login/i.test(e.message))clearSession();}finally{if(refresh){refresh.disabled=false;refresh.textContent=label||'Refresh plan';}}}
function startPolling(){clearInterval(state.poller);if(!state.token)return;state.poller=setInterval(async()=>{try{const d=await api({action:'get_plan',token:state.token});if(d.version>state.version){toast('Your event plan has been updated. Select Refresh plan to view it.');state.version=d.version;}}catch{}},8000);}
document.addEventListener('DOMContentLoaded',()=>{const date=$('[name=date]');if(date)date.min=new Date().toISOString().split('T')[0];$('#planner-form')?.addEventListener('submit',generateEvent);$('#auth-form')?.addEventListener('submit',handleAuth);$('#auth-switch')?.addEventListener('click',()=>openAuth($('#auth-form').dataset.mode==='login'?'signup':'login'));$('#auth-modal')?.addEventListener('click',e=>{if(e.target.closest('.close-modal')||e.target.classList.contains('modal-backdrop'))closeAuth();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#auth-modal')?.hidden)closeAuth();});$('.nav-toggle')?.addEventListener('click',()=>$('nav')?.classList.toggle('open'));document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{$('[name=eventType]').value=b.textContent;$('[name=eventType]').focus();});updateAuthUI();if($('#my-plan')){try{const cached=JSON.parse(localStorage.getItem('eventwise_current_plan')||'null');if(cached?.plan)displayEventPlan(cached.plan,cached);}catch{}if(state.token)getSavedPlan();}});

document.addEventListener('DOMContentLoaded',()=>{
  const sections=[...document.querySelectorAll('.section')].filter(section=>section.id!=='my-plan');
  sections.forEach(section=>section.classList.add('reveal'));
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
    if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}
  }),{threshold:.12});
  sections.forEach(section=>observer.observe(section));
});
